development:
  adapter: postgresql
  encoding: unicode
  database: wallet
  pool: 5
  username: j
  password: 
    
test:
  adapter: postgresql
  encoding: unicode
  database: wallet
  pool: 5
  username: j
  password: 